base_url: https://api.crowdin.com
base_path: .

files:
  -
    source: app/src/main/res/values/strings.xml
    translation: app/src/main/res/values-%two_letters_code%/%original_file_name%
    languages_mapping:
      two_letters_code:
        es-MX: es-rMX
        pt-BR: pt-rBR
        zh-TW: zh-rTW
